from .eztrack_interface import EzTrackFreezingBehaviorInterface
from .zaki_2024_edf_interface import Zaki2024EDFInterface
from .minian_segmentation_interface import MinianSegmentationInterface
from .zaki_2024_sleep_classification_interface import Zaki2024SleepClassificationInterface
from .miniscope_imaging_interface import MiniscopeImagingInterface